services:
  api:
    image: dmshved/todo:v1.0
    container_name: api
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtOptions__SigningKey=hit-the-road-jack-and-don-t-you-come-back-no-more-no-more-no-more-no-more
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    container_name: todo.database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ToDoDb"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=ToDoDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
